# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flightprice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://flightprice.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b0c0c0b40be444f585ee24ffd18b4875 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_781d3390e2e74384bc3465719f2b5c17 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: flightprice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0c0c0b40be444f585ee24ffd18b4875 }}/flightfare:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flightprice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_448edde38c1e433f93268838c759068c }}
        images: 'flightprice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0c0c0b40be444f585ee24ffd18b4875 }}/flightfare:${{ github.sha }}'